id = "just"
name = "Justfile"
description = "Justfile language support"
version = "0.2.0"
schema_version = 1
authors = [
  "Jack Taylor <j@jackt.io>",
  "Matt Robenolt <m@robenolt.com>",
]
repository = "https://github.com/jackTabsCode/zed-just"

[grammars.just]
repository = "https://github.com/casey/tree-sitter-just"
rev = "5685543a6e64f66335e25518c9ae8ffa1dae3d01"

[language_servers.just-lsp]
name = "just-lsp"
languages = ["Just"]
