; File autogenerated by build-queries-nvim.py; do not edit

; Specify nested languages that live within a `justfile`

; FIXME: these are not compatible with helix due to precedence

; ================ Always applicable ================

; Highlight the RHS of `=~` as regex
((regex_literal
  (_) @content)
  (#set! language "regex"))

; ================ Global defaults ================

; Default everything to be bash
(recipe_body
  !shebang
  ((recipe_line)) @content
  (#set! language "bash"))


(external_command
  (command_body) @content
  (#set! language "bash"))

; ================ Global language specified ================
; Global language is set with something like one of the following:
;
;    set shell := ["bash", "-c", ...]
;    set shell := ["pwsh.exe"]
;
; We can extract the first item of the array, but we can't extract the language
; name from the string with something like regex. So instead we special case
; two things: powershell, which is likely to come with a `.exe` attachment that
; we need to strip, and everything else which hopefully has no extension. We
; separate this with a `#match?`.
;
; Unfortunately, there also isn't a way to allow arbitrary nesting or
; alternatively set "global" capture variables. So we can set this for item-
; level external commands, but not for e.g. external commands within an
; expression without getting _really_ annoying. Should at least look fine since
; they default to bash. Limitations...
; See https://github.com/tree-sitter/tree-sitter/issues/880 for more on that.

(source_file
  (setting "shell" ":=" "[" (string) @_langstr
    (#match? @_langstr ".*(powershell|pwsh|cmd).*")
    (#set! language "powershell"))
  [
    (recipe
      (recipe_body
        !shebang
        ((recipe_line)) @content))

    (assignment
      (expression
        (value
          (external_command
            (command_body) @content))))
  ])

(source_file
    (setting "shell" ":=" "[" (string) @language
    (#not-match? @language ".*(powershell|pwsh|cmd).*"))
  [
    (recipe
      (recipe_body
        !shebang
        ((recipe_line)) @content))

    (assignment
      (expression
        (value
          (external_command
            (command_body) @content))))
  ])

; ================ Recipe language specified ================

; Set highlighting for recipes that specify a language, using the exact name by default
(recipe_body ;
  (shebang ;
    (language) @language)
    ((recipe_line)) @content
  (#not-any-of? @language "python3" "nodejs" "node"))

; Transform some known executables

; python3 -> python
(recipe_body
  (shebang
    (language) @_lang)
  ((recipe_line)) @content
  (#eq? @_lang "python3")
  (#set! language "python"))

; node/nodejs -> javascript
(recipe_body
  (shebang
    (language) @_lang)
  ((recipe_line)) @content
  (#any-of? @_lang "node" "nodejs")
  (#set! language "javascript"))
